before:
  hooks:
    - go mod download

builds:
  - main: ./cmd/codeowners
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

release:
  github:
    owner: wompipomp
    name: codeowners

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^build:'
      - '^deps:'
      - '(?i)typo'
